# Generated by Django 3.2.2 on 2021-05-16 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_auto_20210516_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='lastname',
        ),
    ]
