# Generated by Django 3.1.7 on 2021-03-08 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizza',
            options={'verbose_name_plural': 'pizza'},
        ),
    ]
