# Generated by Django 3.1.7 on 2021-03-08 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria_app', '0002_auto_20210308_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='name',
            field=models.CharField(choices=[('Peperroni', 'Peperroni'), ('Chickenk', 'Chicken'), ('Beef', 'Beef'), ('Vegetarian', 'Vegetable')], default='Chickenk', max_length=50),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('small', 'small'), ('medium', 'medium'), ('large', 'large'), ('extra large', 'extra large')], default='small', max_length=50)),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzeria_app.pizza')),
            ],
        ),
    ]
