# Generated by Django 3.1.7 on 2021-03-08 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria_app', '0003_auto_20210308_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topping',
            name='pizza',
        ),
        migrations.AddField(
            model_name='pizza',
            name='toppings',
            field=models.ManyToManyField(to='pizzeria_app.Topping'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pizza',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pizzeria_app.topping'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='topping',
            name='name',
            field=models.CharField(choices=[('Onion', 'Onion'), ('Beef', 'Beef'), ('Chicken', 'Chicken'), ('Vegetables', 'Vegetables')], default='Onion', max_length=50),
        ),
    ]
