# Generated by Django 3.1.6 on 2021-03-09 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria_app', '0004_auto_20210308_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pizza',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pizzeria_app.pizza'),
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='toppings',
        ),
        migrations.AddField(
            model_name='pizza',
            name='toppings',
            field=models.CharField(choices=[('Onion', 'Onion'), ('Beef', 'Beef'), ('Chicken', 'Chicken'), ('Vegetables', 'Vegetables')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Topping',
        ),
    ]
