# Generated by Django 3.1.7 on 2021-03-09 10:15

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria_app', '0005_auto_20210309_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='toppings',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Onion', 'Onion'), ('Beef', 'Beef'), ('Chicken', 'Chicken'), ('Vegetables', 'Vegetables')], default='Onion', max_length=29),
        ),
    ]
