# Generated by Django 3.1.7 on 2021-03-09 10:18

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria_app', '0006_auto_20210309_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='toppings',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Onion', 'Onion'), ('Beef', 'Beef'), ('Chicken', 'Chicken'), ('Vegetables', 'Vegetables')], max_length=29, null=True),
        ),
    ]
