# Generated by Django 3.1.7 on 2021-03-09 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria_app', '0007_auto_20210309_1018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_name',
            new_name='name_of_orderer',
        ),
    ]
